<?php
/**
 * Paging Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-6 columns left">
        <a href="<?= $page_url; ?>?page=post" class="button tiny secondary radius">Previous</a>
    </div>
    <div class="large-6 columns">
        <a href="<?= $page_url; ?>?page=post" class="button tiny secondary radius right">Next</a>
    </div>
</div>
