<?
/**
 * Rendered Page for Test
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
?>
<?
/**
 * Wrap Header
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
?>
<div>
    <p>Header</p>
</div>
<?
/**
 * Wrap Body
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
?>
<article>
    <?
    /**
     * Test
     *
     * @package    Molajo
     * @license    http://www.opensource.org/licenses/mit-license.html MIT License
     * @copyright  2014 Amy Stephen. All rights reserved.
     */
    ?>
    <div>
        <p>Header</p>
    </div>
    <?
    /**
     * Test
     *
     * @package    Molajo
     * @license    http://www.opensource.org/licenses/mit-license.html MIT License
     * @copyright  2014 Amy Stephen. All rights reserved.
     */
    ?>
    <div>
        <p>Body</p>
    </div>
    <?
    /**
     * Test
     *
     * @package    Molajo
     * @license    http://www.opensource.org/licenses/mit-license.html MIT License
     * @copyright  2014 Amy Stephen. All rights reserved.
     */
    ?>
    <div>
        <p>Footer</p>
    </div>
</article>
<?
/**
 * Wrap Footer
 *
 * @package    Molajo
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 * @copyright  2014 Amy Stephen. All rights reserved.
 */
?>
<div>
    <p>Footer</p>
</div>

