<?php
/**
 * Video Template - Sample Foundation 5 Template for Molajito Rendering
 *https://www.youtube.com/watch?v=<?= $this->row->link; ?>
 * http://www.youtube.com/embed/aiBt44rrslw
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="flex-video widescreen vimeo">
    <iframe src="<?= $this->row->link; ?>" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
    </iframe>
</div>
