<?php
/**
 * Blog Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<article>
    <h3>
        <a href="<?= $this->row->current_url; ?>">
            <?= $this->row->title; ?>
        </a>
    </h3>

    <h6>Written by:
        <a href="<?= $this->runtime_data->route->author . '/'; ?>">
            <?= $this->row->author; ?>
        </a>
        on <?= $this->row->published; ?>.
    </h6>

    <?= $this->row->readmore; ?>

    <a class="right" href="<?= $this->row->current_url; ?>">
        Read More →
    </a>
</article>
