<div class="row">
    <!-- Profile -->
    <div class="large-7 columns">
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Profile/Body.phtml'; ?>
    </div>
    <!-- Gallery -->
    <div class="large-5 columns">
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Gallery/Header.phtml'; ?>
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Gallery/Body.phtml'; ?>
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Gallery/Footer.phtml'; ?>
    </div>
</div>
