<?php
/**
 * Categories Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
    <li>
        <a href="<?= $this->runtime_data->route->blog; ?>&category=personal">
            Personal
        </a>
    </li>
    <li>
        <a href="<?= $this->runtime_data->route->blog; ?>&category=business">
            Business
        </a>
    </li>
    <li>
        <a href="<?= $this->runtime_data->route->blog; ?>&category=rant">
            Rant
        </a>
    </li>

