<?php
/**
 * Navbar Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-3 columns">
        <h1>
            <a href="<?= $this->row->home_link ?>">
                <img src="http://placehold.it/400x100&text=Blog" />
            </a>
        </h1>
    </div>
    <div class="large-9 columns">
        <ul class="right button-group">
