<li><img data-caption="caption here..." src="http://placehold.it/100x100/00FFFF/e3e3e3"/></li>
<li><img data-caption="caption here..." src="http://placehold.it/100x100/996633/e3e3e3"/></li>
<li><img data-caption="caption here..." src="http://placehold.it/100x100/FF3399/e3e3e3"/></li>
<li><img data-caption="caption here..." src="http://placehold.it/100x100/9933FF/e3e3e3"/></li>
<li><img data-caption="caption here..." src="http://placehold.it/100x100/33CC33/e3e3e3"/></li>
<li><img data-caption="caption here..." src="http://placehold.it/100x100/0066CC/e3e3e3"/></li>
<li><img data-caption="caption here..." src="http://placehold.it/100x100/003300/e3e3e3"/></li>
<li><img data-caption="caption here..." src="http://placehold.it/100x100/666699/e3e3e3"/></li>
<li><img data-caption="caption here..." src="http://placehold.it/100x100/CC0066/e3e3e3"/></li>

