---
title : Valentine
subtitle: Wilt Thou be Mine?
author: Amy Stephen
published: 2014-02-14
categories : business
tags : valentine
featured : 0
horizontal_image: http://placehold.it/400x300&text=[<3]
---

<p>Apple pie biscuit chocolate caramels. Dragée sweet cupcake wafer gummies bear claw toffee caramels I love. Dragée tootsie roll unerdwear.com. Gummi bears tootsie roll cake I love cookie.</p>
{{readmore}}
<p>Will you be my valentine cupcake ipsum dolor sit amet dragée? Will you love me til I die, Tiramisu? What if I love brownies and I love I love dragée? Will you still be mine?

<p>Maybe I should mention my involvement with cookie oat cake dragée gummi bears tart I love jelly beans soufflé. I love candy canes jujubes.</p>

<p>Caramels apple pie cotton candy cupcake tart sesame snaps. Tiramisu candy bear claw. Chupa chups I love jujubes I love apple pie marshmallow. Apple pie tart dessert powder sweet roll tiramisu.</p>

<p>I will always be true to you.</p>
