<?php
/**
 * Profile Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<h3>Amy Stephen</h3>
<p>Topping tiramisu brownie. Cotton candy wafer chocolate cake gummi bears pie unerdwear.com chupa chups wafer.</p>
<p>Cake ice cream cupcake chupa chups tootsie roll cotton candy cupcake.</p>

<p><ul class="inline-list">
    <li><a class="webicon mail" href="mailto:AmyStephen@gmail.com">Email</a></li>
    <li><a class="webicon twitter" href="http://Twitter.com/AmyStephen">Twitter</a></li>
    <li><a class="webicon github" href="https://Github.com/AmyStephen">Github</a></li>
    <li><a class="webicon googleplus" href="https://plus.google.com/+AmyStephen">Google+</a></li>
</ul></p>
