<?php
/**
 * Foundation 5 Sample Theme for Molajito Rendering
 *
 * @package    Molajito
 * @link       Molajito
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><?= $this->runtime_data->parameters->site_title ?></title>
    <link rel="stylesheet" href="/Foundation5/webicons/webicons.css"/>
    <link rel="stylesheet" href="/Foundation5/css/foundation.css"/>
    <link rel="stylesheet" href="/Foundation5/css/custom.css"/>
    <script src="/Foundation5/js/vendor/modernizr.js"></script>
</head>
<body>
<div class="page-wrap">
    {I Navbar I}
    {I Breadcrumbs I}
    {I page=<?= $this->row->page_name; ?> I}
</div>
    {I Footer I}
<script src="/Foundation5/js/vendor/jquery.js"></script>
<script src="/Foundation5/js/foundation.min.js"></script>
<script src="/Foundation5/js/foundation/foundation.orbit.js"></script>
<script src="/Foundation5/js/foundation/foundation.reveal.js"></script>
<script src="/Foundation5/js/foundation/foundation.clearing.js"></script>
<script>
    $(document).foundation();
</script>
</body>
</html>
