<?php
/**
 * Breadcrumbs Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<li>
<?php if ($this->row->current == 1) {
} else {  ?>
<a href="<?= $this->row->url; ?>">
<?php } ?>
HOME
<?php if ($this->row->current == 1) {
    } else {  ?>
</a>
<?php }
