<?php
/**
 * Breadcrumbs Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */

if ($this->row->total_rows > 1) {
?>
    <li>
    <?php if ($this->row->last_row == 1) {
} else {
    ?>
    <a href="<?= $this->row->link; ?>">
<?php } ?>
    <?= $this->row->text; ?>
    <?php if ($this->row->last_row == 1) {
    } else {
        ?>
        </a>
    <?php
    }
}
