<?php
/**
 * Featured Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="panel">
    <h5>
        <a href="<?= $this->runtime_data->route->post . '&name=' . $this->row->filename; ?>">
            <?= $this->row->title; ?>
        </a>
    </h5>

    <?= $this->row->readmore; ?>
</div>
