<?php
/**
 * Featured Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="panel">
    <h5>
        <a href="<?= $this->row->current_url ?>">
            <?= $this->row->title; ?>
        </a>
    </h5>
    <?= $this->row->snippet; ?>

    <a class="right" href="<?= $this->row->current_url ?>">
        Read More →
    </a>
</div>
