<?php
/**
 * Featured Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="panel">
    <h5><a href="<?= $this->runtime_data->route->post; ?>">Title</a></h5>
    <p>Cupcake ipsum dolor sit amet wafer cake cupcake. Danish bonbon pie unerdwear.com chocolate cake muffin chocolate bar toffee. Caramels gummi.</p>
    <a href="<?= $this->runtime_data->route->post; ?>">Read More →</a>
</div>
