<?php
/**
 * Pagination Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-12 columns">
        <div class="pagination-centered">
            <ul class="pagination">
                <li class="arrow"><a href="<?= $this->row->first_page_link; ?>">&laquo; &laquo;</a></li>
                <?php if ((int) $this->row->previous_page_number == 0) : ?>
                    <li class="arrow unavailable"></li>
                <?php else : ?>
                    <li class="arrow"><a href="<?= $this->row->previous_page_link; ?>">&laquo;</a></li>
                <?php endif; ?>

                <?php if ((int) $this->row->next_page_number == 0) : ?>
                    <li class="arrow unavailable"><a href="">&laquo;</a></li>
                <?php else : ?>
                    <li class="arrow"><a href="<?= $this->row->next_page_link; ?>">&raquo;</a></li>
                <?php endif; ?>
                <li class="arrow"><a href="<?= $this->row->last_page_link; ?>">&raquo; &raquo;</a></li>
            </ul>
        </div>
    </div>
</div>
