<?php
/**
 * Pagination Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-12 columns">
        <div class="pagination-centered">
            <ul class="pagination">
                <?php if ((int)$this->row->first_page_number == (int)$this->row->current_page_number) : ?>
                    <li class="arrow unavailable"></li>
                <?php else : ?>
                    <li class="arrow"><a href="<?= $this->row->first_page_link; ?>">&laquo; &laquo;</a></li>
                <?php endif; ?>

                <?php if ((int)$this->row->previous_page_number == (int)$this->row->current_page_number) : ?>
                    <li class="arrow unavailable"></li>
                <?php else : ?>
                    <li class="arrow"><a href="<?= $this->row->previous_page_link; ?>">&laquo;</a></li>
                <?php endif; ?>

                <?php
                for ($i = $this->row->start_links_page_number;
                     $i < $this->row->stop_links_page_number + 1;
                     $i ++) {

                    if ((int)$i == (int)$this->row->current_page_number) : ?>
                        <li class="current">
                    <?php else : ?>
                        <li>
                    <?php endif; ?>
                    <a href="<?= $this->row->page_links_array[$i]; ?>"><?= $i; ?></a></li>
                <?php } ?>

                <?php if ((int)$this->row->next_page_number == (int)$this->row->current_page_number) : ?>
                    <li class="arrow unavailable"><a href="">&raquo;</a></li>
                <?php else : ?>
                    <li class="arrow"><a href="<?= $this->row->next_page_link; ?>">&raquo;</a></li>
                <?php endif; ?>

                <?php if ((int)$this->row->last_page_number == (int)$this->row->current_page_number) : ?>
                    <li class="arrow unavailable"><a href="">&raquo;</a></li>
                <?php else : ?>
                    <li class="arrow"><a href="<?= $this->row->last_page_link; ?>">&raquo; &raquo;</a></li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</div>
