<?php
/**
 * Pagination Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-12 columns">
    <h3>Note: Pagination Class not brought in yet.</h3>
        <div class="pagination-centered">
            <ul class="pagination">
                <li class="arrow unavailable"><a href="">&laquo;</a></li>
                <li class="current"><a href="">1</a></li>
                <li><a href="">2</a></li>
                <li><a href="">3</a></li>
                <li><a href="">4</a></li>
                <li class="unavailable"><a href="">&hellip;</a></li>
                <li><a href="">12</a></li>
                <li><a href="">13</a></li>
                <li class="arrow"><a href="">&raquo;</a></li>
            </ul>
        </div>
    </div>
</div>
