<?php
/**
 * Author Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="panel">
    <h4>
        <?= $this->row->name ?>
    </h4>

    <p>
        <?= $this->row->snippet ?>
    </p>

    <ul class="inline-list">
        <?php if ($this->row->email !== '') { ?>
            <li>
                <a class="webicon mail" href="mailto:<?= $this->row->email ?>">
                    {T Email T}
                </a>
            </li>
        <?php } ?>
        <?php if ($this->row->twitter !== '') { ?>
            <li>
                <a class="webicon twitter" href="http://Twitter.com/<?= $this->row->twitter ?>">
                    Twitter
                </a>
            </li>
        <?php } ?>
        <?php if ($this->row->github !== '') { ?>
            <li>
                <a class="webicon github" href="https://Github.com/<?= $this->row->github ?>">
                    Github
                </a>
            </li>
        <?php } ?>
        <?php if ($this->row->googleplus !== '') { ?>
            <li>
                <a class="webicon googleplus" href="https://plus.google.com/<?= $this->row->googleplus ?>">
                    Google+
                </a>
            </li>
        <?php } ?>
    </ul>
</div>
