<?php
/**
 * Horizontal Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="large-4 columns">

    <img src="<?= $this->row->horizontal_image; ?>" />

    <h4>
        <a href="<?= $this->row->current_url; ?>">
            <?= $this->row->title; ?>
        </a>
    </h4>

    <?= $this->row->snippet; ?>
</div>
