<?php
/**
 * Horizontal Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="large-4 columns">
    <img src="http://placehold.it/400x300&text=[img]" />
    <h4>
        <a href="<?= $this->runtime_data->route->post . '&name=' . $this->row->filename; ?>">
            <?= $this->row->title; ?>
        </a>
    </h4>
    <?= $this->row->snippet; ?>
</div>
