<?php
/**
 * Comments Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-12 columns">
        <p>
            <img class="right" src="http://placehold.it/50x50&text=[img]" />
            <strong>Some Person said:</strong>:
            Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit
        </p>
    </div>
</div>
