<?php
/**
 * Maps Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<h5>Map</h5>
<p>
    <iframe src="<?= $this->row->map; ?>" width="200" height="200" frameborder="0" style="border:0"></iframe>
</p>
<p>
<?= $this->row->map_address; ?>
</p>

