<?php
/**
 * Maps Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<h5>Map</h5>
<p>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3020.1766407600185!2d-96.68290400000004!3d40.802112000000015!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8796be60e05420c7%3A0xe9ca08c6602dada7!2sSunken+Gardens!5e0!3m2!1sen!2sus!4v1396636781204" width="200" height="200" frameborder="0" style="border:0"></iframe>
</p>
<p>
    Sunken Gardens<br>
    S 27th St<br>
    Lincoln, NE 68502
</p>

