---
title : Gumdrop
subtitle: Need I say more?
author: Amy Stephen
published: 2014-01-20
categories : rant
tags : gumdrop
---

<p>I love cupcake gummies wafer lollipop jelly muffin carrot cake. Dragée sesame snaps gingerbread unerdwear.com. I love dragée sesame snaps chocolate cake gingerbread candy tootsie roll. Jujubes candy canes liquorice jelly chupa chups I love. Marzipan I love candy dragée donut powder jelly-o jelly beans. Jelly sesame snaps brownie.</p>
{{pagebreak}}

<p>Biscuit chupa chups cotton candy cheesecake powder chocolate cake cheesecake chupa chups jelly-o. Marzipan soufflé cupcake sweet marzipan bear claw fruitcake. Bear claw cake caramels. Toffee oat cake wafer lollipop sweet roll macaroon liquorice toffee chocolate cake. Icing lemon drops sugar plum danish. Pastry ice cream I love carrot cake I love cheesecake. Sugar plum jelly beans cheesecake. Brownie cupcake fruitcake toffee gummi bears. Jelly-o apple pie cotton candy dragée jelly beans chocolate.</p>
