---
title : Abducted
subtitle: Of course by aliens!
author: Amy Stephen
published: 2014-04-01
categories : rant
tags : cupcake
featured : 0
video : http://www.youtube.com/embed/y6Sxv-sUYtM
horizontal_image: http://placehold.it/400x300&text=[Yikes]
---

<p>Croissant cookie powder halvah marzipan cake wafer pastry. Tiramisu soufflé unerdwear.com cupcake liquorice caramels. Cake candy canes oat cake.</p>
    {{readmore}}
<p>Lollipop lollipop cake. Fruitcake dragée marshmallow chocolate cake dragée tiramisu powder bear claw gummies. Gummies dragée danish jujubes cotton candy cake cupcake marzipan topping.</p>
