<?php
/**
 * Paging Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-6 columns left">
        <?php if ($this->row->previous_url !== '') { ?>
            <a href="<?= $this->row->previous_url; ?>" class="button tiny secondary radius">{T Previous T}</a>
        <?php } ?>
    </div>
    <div class="large-6 columns">
        <?php if ($this->row->next_url !== '') { ?>
            <a href="<?= $this->row->next_url; ?>" class="button tiny secondary radius right">{T Next T}</a>
        <?php } ?>
    </div>
</div>
