<?php
/**
 * Author Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="panel">
    <h5><a href="<?= $this->runtime_data->route->contact; ?>">Amy Stephen</a></h5>

    <p><img class="right" src="http://placehold.it/75x75&text=[img]" />
        Capicola short ribs minim salami nulla nostrud pastrami. Nulla corned beef sunt ball tip, qui bresaola enim jowl.
        Capicola short ribs minim salami nulla nostrud pastrami.
    </p>

    <ul class="inline-list">
        <li><a class="webicon github small" href="https://Github.com/AmyStephen">Github</a></li>
        <li><a class="webicon twitter small" href="http://Twitter.com/AmyStephen">Twitter</a></li>
        <li><a class="webicon googleplus small" href="https://plus.google.com/+AmyStephen">Google+</a></li>
        <li><a class="webicon mail small" href="mailto:AmyStephen@gmail.com">Email</a></li>
    </ul>
</div>
