<?php
/**
 * Contact Page - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-9 columns">
        {I Contact I}
    </div>
    <div class="large-3 columns">
        {I Maps I}
    </div>
</div>
