<footer class="row">
    <div class="large-12 columns">
        <hr />
        <div class="row">
            <div class="large-6 columns">
                <p>Molajo is © Copyright Amy Stephen. All rights reserved.</p>
            </div>
            <div class="large-6 columns">
                <ul class="inline-list right">
                    <li><a href="<?= $home; ?>">Home</a></li>
                    <li><a href="<?= $blog; ?>">Blog</a></li>
                    <li><a href="<?= $about; ?>">About</a></li>
                    <li><a href="<?= $contact; ?>">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
