<?php
/**
 * Footer Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<footer class="row site_footer">
    <div class="large-12 columns">
        <div class="row">
            <div class="large-6 columns">
                <p><?= $this->runtime_data->parameters->copyright; ?></p>
            </div>
            <div class="large-6 columns">
                <ul class="inline-list right">
