<h3>Want to get in Touch?</h3>

<p>I would love to hear from you. You can either cupcake liquorice caramels or you can cake candy canes. <em>it's your choice</em>.</p>

<div class="row">
    <div class="large-12 columns">
        <h5 class="title">Contact Me</h5>
        <div class="content" data-slug="panel1">
            <form>
                <div class="row collapse">
                    <div class="large-2 columns">
                        <label class="inline">Your Name</label>
                    </div>
                    <div class="large-10 columns">
                        <input type="text" id="yourName" placeholder="Pumpkin Smith">
                    </div>
                </div>
                <div class="row collapse">
                    <div class="large-2 columns">
                        <label class="inline"> Your Email</label>
                    </div>
                    <div class="large-10 columns">
                        <input type="text" id="yourEmail" placeholder="PumpkinSmith@example.com">
                    </div>
                </div>
                <label>What's up?</label>
                <textarea rows="4"></textarea>
                <button type="submit" class="radius button right">Submit</button>
            </form>
        </div>
    </div>
</div>
