<?php
/**
 * Contact Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<h3><?= $this->row->title; ?></h3>

<?= $this->row->content; ?>

<div class="row">
    <div class="large-12 columns">
        <h5 class="title">{T Contact Me T}</h5>
        <div class="content" data-slug="panel1">
            <form>
                <div class="row collapse">
                    <div class="large-2 columns">
                        <label class="inline">{T Your Name T}</label>
                    </div>
                    <div class="large-10 columns">
                        <input type="text" id="yourName" placeholder="{T Your Name T}">
                    </div>
                </div>
                <div class="row collapse">
                    <div class="large-2 columns">
                        <label class="inline">{T Your Email T}</label>
                    </div>
                    <div class="large-10 columns">
                        <input type="text" id="yourEmail" placeholder="{T Your Email T}">
                    </div>
                </div>
                <label>{T Your Message T}</label>
                <textarea rows="4"></textarea>
                <button type="submit" class="radius button right">{T Submit T}</button>
            </form>
        </div>
    </div>
</div>
