<?php
/**
 * Action Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-12 columns">
        <div class="panel">
            <h4><?= $this->row->title; ?></h4>
            <div class="row">
                <div class="large-9 columns">
                    <?= $this->row->content; ?>
                </div>
                <div class="large-3 columns">
                    <a href="<?= $this->runtime_data->route->contact; ?>"
                       class="radius button right"><?= $this->row->button_text; ?></a>
                </div>
            </div>
        </div>
    </div>
</div>
