<div class="row">
    <div class="large-12 columns">

        <div class="panel">
            <h4>Get in touch!</h4>

            <div class="row">
                <div class="large-9 columns">
                    <p>We'd love to hear from you, you cupcake, you.</p>
                </div>
                <div class="large-3 columns">
                    <a href="<?= $contact; ?>" class="radius button right">Contact Us</a>
                </div>
            </div>
        </div>

    </div>
</div>

