<?php
/**
 * Blog Page - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-9 columns" role="content">
        {I Blog I}
        {I Pagination I}
    </div>
    <aside class="large-3 columns">
        {I Featured I}
        {I Categories I}
        {I Tags I}
    </aside>
</div>
