<div class="row">
    <!-- Blog -->
    <div class="large-9 columns" role="content">
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Blog/Body.phtml'; ?>
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Blog/Body.phtml'; ?>
        <!-- Pagination -->
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Pagination/Custom.phtml'; ?>
    </div>
    <aside class="large-3 columns">
        <!-- Categories -->
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Categories/Header.phtml'; ?>
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Categories/Body.phtml'; ?>
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Categories/Footer.phtml'; ?>
        <!-- Featured -->
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Featured/Body.phtml'; ?>
    </aside>
</div>
