<?php
/**
 * Blog Page - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-9 columns" role="content">
        {I Blog I}
        <?php if (class_exists('\Molajo\Pagination')) : ?>
            {I Pagination I}
        <?php else : ?>
            <h3>Pagination Template is Disabled</h3>
            <p>To enable: include the Molajo/Pagination class in Composer.json and update.</p>
        <?php endif; ?>
    </div>
    <aside class="large-3 columns">
        {I Categories I}
        {I Tags I}
        {I Featured I}
    </aside>
</div>
