<div class="row">
    <div class="large-9 push-3 columns">
        <!-- Post -->
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Post/Body.phtml'; ?>

        <!-- Comments -->
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Comments/Header.phtml'; ?>
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Comments/Body.phtml'; ?>
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Comments/Body.phtml'; ?>
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Comments/Body.phtml'; ?>
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Comments/Footer.phtml'; ?>

        <!-- Paging -->
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Paging/Custom.phtml'; ?>
    </div>
    <div class="large-3 pull-9 columns">
        <!-- Categories -->
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Categories/Header.phtml'; ?>
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Categories/Body.phtml'; ?>
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Categories/Footer.phtml'; ?>

        <!-- Author -->
        <?php include FOLDER_BASE . '/Views/Foundation5/Templates/Author/Body.phtml'; ?>
    </div>
</div>
