<?php
/**
 * Post Page - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 *
 *                     {I Paging I}
 *                     {I Author I}
 */
?>
<div class="row">
    <div class="large-9 push-3 columns">
        {I Post I}
        {I Comments I}
        {I Paging I}
    </div>
    <div class="large-3 pull-9 columns">
        {I Categories I}
        {I Author I}
    </div>
</div>
