<?php
/**
 * Orbit Template - Sample Foundation 5 Template for Molajito Rendering
 *
 * @package    Molajo
 * @copyright  2014 Amy Stephen. All rights reserved.
 * @license    http://www.opensource.org/licenses/mit-license.html MIT License
 */
?>
<div class="row">
    <div class="large-12 columns">
        <ul class="example-orbit" data-orbit>
            <li><img src="http://placehold.it/1000x400&amp;text=[%20img%201%20]"></li>
            <li><img src="http://placehold.it/1000x400&amp;text=[%20img%202%20]"></li>
            <li><img src="http://placehold.it/1000x400&amp;text=[%20img%203%20]"></li>
        </ul>
    </div>
</div>
