<div class="row">
    <div class="large-3 columns">
        <h1><img src="http://placehold.it/400x100&text=Logo" /></h1>
    </div>
    <div class="large-9 columns">
        <ul class="right button-group">
            <li><a href="<?= $home; ?>" class="button">Home</a></li>
            <li><a href="<?= $blog; ?>" class="button">Blog</a></li>
            <li><a href="<?= $about; ?>" class="button">About</a></li>
            <li><a href="<?= $contact; ?>" class="button">Contact</a></li>
        </ul>
    </div>
</div>
